### ISSUE TITLE
Check that all keys in the specified key field are valid

### ISSUE THREAD

**Issue by AlmightyYakob** [multinet-app/multinet-server#357]
Once https://github.com/multinet-app/multinet-client/pull/54 is merged, users will be able to specify their own key columns, but currently there's nothing in place to verify that the keys in the specified key column conform to the [rules](https://www.arangodb.com/docs/stable/data-modeling-naming-conventions-document-keys.html) that ArangoDB places on keys.

**Comment by waxlamp** [comment]
This is pretty high priority, since without this we can leave the system in a broken state.
