### ISSUE TITLE
Don't call util.require_db before each request

### ISSUE THREAD

**Issue by AlmightyYakob** [multinet-app/multinet-server#362]

**Comment by JackWilb** [comment]
I think we'll want to still call this function to make sure the db is up, but once per request, not several times. @waxlamp had also mentioned that we might cache the result for some time period so that we can reduce the calls even more

**Comment by AlmightyYakob** [comment]
Closed via https://github.com/multinet-app/multinet-server/pull/363/commits/6c588c802d99762d04805a43ebf2e1c12b063f3d
