### ISSUE TITLE
substitute {graph} for actual name in nested-json and newick uploads in swagger. 

### ISSUE THREAD

**Issue by curtislisle** [multinet-app/multinet-server#382]
When testing the uploader API endpoints (for uploading newick and nested-json) through the swagger interface, the graph name is not substituted. For example this is the curl that is attempted:

curl -X POST "https://api.multinet.app/api/nested_json/Curt/{graph}" -H "accept: application/json" -H "Content-Type: text/plain" -d "{\"edge_fields\": [\"weight\"], \"node_fields\": [\"node name\", \"node weight\"], \"node_data\": {...***content deleted for brevity***...}"

NOTE:  Please see how the graph name wasn't correctly substituted for {graph}.   

This happens on the nested-json upload and the newick upload.  I didn't test other upload methods yet.    What I mean is that I entered a graph name as the required parameter and pasted in the file content but received a run time error when executing this from the swagger interface.  When I copied the text to my terminal, and substituted the graph name in the curl call, the call was successful.

**Comment by waxlamp** [comment]
Ah thanks for the detail here, Curt. We'll look into this.
