### ISSUE TITLE
Install error in uwsgi when running pipenv install

### ISSUE THREAD

**Issue by kirangadhave** [multinet-app/multinet-server#383]
Operating System: MacOS Catalina
Error message: 
<img width="1920" alt="Screen Shot 2020-05-15 at 6 25 20 PM" src="https://user-images.githubusercontent.com/14944083/82114692-93ee4a80-971b-11ea-8b5c-cf1e6d3a7c94.png">

This was an error with LLVM compiler version, i had to point to a proper version:
`export CC=/usr/bin/llvm-gcc`

This workaround is mentioned [here](https://stackoverflow.com/a/26386519/6109589).

**Comment by waxlamp** [comment]
I'm not sure there's much we can do to prevent errors like this that depend on the local build chain. Do you think it makes sense to mention this workaround in our docs for iOS?
