### ISSUE TITLE
More fine-grained control over allowed origins for cookies

### ISSUE THREAD

**Issue by waxlamp** [multinet-app/multinet-server#384]
We're using Flask-CORS currently to allow a whitelist of domains to send cookies for authentication (and therefore for the majority of API access). We're looking for a way to have the equivalent of the allowed origins being set to `*` while still allowing credential transfer (which is not allowed by Flask-CORS).

There's a possibility we can do something like this using the [after_request](https://flask.palletsprojects.com/en/1.1.x/api/#flask.Flask.after_request) hook. This [tutorial](https://dev.to/g33konaut/understanding-cors-aaf) shows in principle how this general idea can work.

Another possibility is to implement the header-based authentication system that, e.g., Girder uses.

We should do the following as part of resolving this issue:
1. Investigate whether there are valid security reasons for Flask-CORS's policy of not allowing the setup we are after.
2. Investigate whether Girder's header-based approach is feasible for us (it may not be if the complexity of implementing it for Multinet is severely higher than our current approach, or if there are security flaws inherent in the approach).
3. Investigate whether the after_request or tutorial approaches would work for Multinet.
4. Decide whether to close this issue as a wontfix, or to implement a chosen solution. It is worth considering as part of this step that as a research project, what we already have so far is likely to be more than sufficient for our purposes.

**Comment by AlmightyYakob** [comment]
Dynamic matching of CORS done on girder: https://github.com/girder/girder/pull/3300
