### ISSUE TITLE
Can't create network from CSV

### ISSUE THREAD

**Issue by alexsb** [multinet-app/multinet-server#390]
I've uploaded two csv tables - fligths and airports - https://drive.google.com/drive/u/0/folders/1H-ackff2ppfXTBsyCAuG_j0WScdkkQQM
and was able to load the csv, but not to connect them up. 

Choose edge table gives me nothing: 

![image](https://user-images.githubusercontent.com/2039375/83085406-0ed33180-a049-11ea-84fd-4689ff5db2d1.png)

This could be misunderstanding the interface, but I also tried to load the csv via the network interface, which wasn't possible.

**Comment by AlmightyYakob** [comment]
@alexsb did you specify the `key` field in the `airports` table to be `iata`? Another issue is that theres no `_from` and `_to` column on the `flights-airports` table (they're `origin` and `destination`). I'm not sure if there's an open issue to allow specifying keys for the `_from` and `_to` rows, but that's probably something that should be supported.

Aside from everything I've just mentioned, it looks like there's errors on the backend relating to this, so I can investigate that as well.
