### ISSUE TITLE
Consider ending use of `dataclasses.asdict`

### ISSUE THREAD

**Issue by AlmightyYakob** [multinet-app/multinet-server#414]
The `asdict` function is actually a bit [slow](https://stackoverflow.com/questions/52229521/why-is-dataclasses-asdictobj-10x-slower-than-obj-dict). A way around this would be to implement `asdict` functions on each dataclass that we have, which returns `__dict__`, and replaces their inherited items with calls to `super().asdict()`. Another approach would be to have a recursive function at the root of each dataclass inheritance tree, which recurses and returns `__dict__` if it finds a dataclass.

**Comment by waxlamp** [comment]
To make this actionable, we will need performance data. If this isn't causing a slowdown for us (as, currently, it doesn't seem to be), we can ignore this at least for now.

Since we're not feeling any slowdown in general, I'd say not to worry about this right now.

Good informational find though.
