### ISSUE TITLE
Refactor arangodb ansible playbook

### ISSUE THREAD

**Issue by AlmightyYakob** [multinet-app/multinet-server#415]
One of the biggest use cases for this is splitting up the readonly user steps from the rest of the playbook, so it can be selectively applied when needed. However, we also want to take a closer look at our current steps against the steps required, and how we can make it more streamlined and error prone.

**Comment by waxlamp** [comment]
We had a brief meeting to discuss this, and we decided the following items should be part of this work:
- tighten the way certain tasks are done (e.g., prefer `restart` to a `stop` followed by a `start`)
- split the tasks up into "sub playbooks" so they can be run independently of each other
- include a "master playbook" that runs everything
- use `ansible-vault` to store necessary secrets for deployment (Arango passwords, cert files, etc.)
