### ISSUE TITLE
Add `require_writer` decorator to the `create_aql_table` api endpoint

### ISSUE THREAD

**Issue by AlmightyYakob** [multinet-app/multinet-server#416]
Once #412 lands, the new `require_writer` decorator should be added to this new endpoint. Relevant api endpoint:

https://github.com/multinet-app/multinet-server/blob/e88f9d42dae5b62e214ce133fd5c0084d03d26c6/multinet/api.py#L46-L54

**Comment by waxlamp** [comment]
Looks like this is done. Can you confirm and close, @AlmightyYakob?

**Comment by AlmightyYakob** [comment]
Indeed it is.
