### ISSUE TITLE
Add endpoints for getting and setting workspace user roles

### ISSUE THREAD

**Issue by AlmightyYakob** [multinet-app/multinet-server#419]
Prerequisite functionality for https://github.com/multinet-app/multinet-client/pull/107

This would be a pair of endpoints that would look something like:

* `GET /api/workspaces/{workspace}/permissions`
* `PUT /api/workspaces/{workspace}/permissions`

The data model for each of these would contain a list of users, and their permission on the workspace. Something like:

```
[
  {
    user: <sub>
    role: <'reader' | 'writer' | 'maintainer' | 'owner'>
  },
  ...
]
```

The workflow for modifying the permissions of a workspace would be as follows:

1. Retrieve list of users with their respective roles
2. Modify list
3. Call `PUT` to set the new permissions

This would obviously be gated behind the `owner` role on a workspace.

**Comment by waxlamp** [comment]
Instead of a list of individual users, would it be better or worse to have something like:

```
{
  owner: <sub>,
  maintainers: [<sub1>, <sub2>, ...],
  writers: [...],
  readers: [...]
}
```

and you would modify the permissions structure just by adding/deleting users from the appropriate lists.

What are the pros/cons of doing it each way?

**Comment by AlmightyYakob** [comment]
> Instead of a list of individual users, would it be better or worse to have something like:
> 
> ```
> {
>   owner: <sub>,
>   maintainers: [<sub1>, <sub2>, ...],
>   writers: [...],
>   readers: [...]
> }
> ```
> 
> and you would modify the permissions structure just by adding/deleting users from the appropriate lists.
> 
> What are the pros/cons of doing it each way?

The approached you laid out is preferred, as we already model the permissions in this way anyway. I'll follow this approach.
