### ISSUE TITLE
Validation Error: embedded newline reported as duplicate key

### ISSUE THREAD

**Issue by curtislisle** [multinet-app/multinet-server#431]
I attempted an import of a large graph.  Four lines in the node file had embedded newlines in the "role" attribute (see attached photo of the json-lines version of the data.  The UI said "Validation error" but browser console indicated error returned as a duplicate key.   This was a "dirty data" upload issue, but it would be great if MultiNet could be more tolerant or provide more robust error messages.  The bad lines in the file have the name AARON LISTON associated with them.  

<img width="986" alt="validation-embedded-newline" src="https://user-images.githubusercontent.com/2152950/87821443-da584680-c83d-11ea-8d57-cb6ef167aa33.png">

[validation_failure.csv.txt](https://github.com/multinet-app/multinet-server/files/4939688/validation_failure.csv.txt)

[validation_failure_fixed.csv.txt](https://github.com/multinet-app/multinet-server/files/4939690/validation_failure_fixed.csv.txt)

**Comment by waxlamp** [comment]
I'm fairly certain what happened was the following: When the "AARON LISTON" lines get broken at the embedded newline character, the CSV appears to have extra lines of data that start with `,male,40,...`. That is, the lines appear to have an empty field, then `male`, then `40`, and so on. Note that your `_key` field is in the second column; that is, those lines appear to all use the value `male` for the key field. There's our duplicate key :)

As I mentioned in our meeting, it is hard to properly catch errors like this in general. The embedded newline simple appears like a completely normal end-of-line in a CSV file--that is, technically, with those broken lines, this file really is a valid CSV. I'm not sure quite what to do about this, other than address such possible problems in our documentation. If you have other ideas, please let us know.

**Comment by curtislisle** [comment]
Aha!  I knew the parsing error was happening, but didn't realize how it was coming up with the duplicate key. I agree that this should be out-of-scope of the code.  We might only want to have a place on the UI for error messages.  I only knew it was a 'duplicate key' by going into the browser javascript console in a debugging session.   recommend closing this issue.

**Comment by waxlamp** [comment]
> I agree that this should be out-of-scope of the code. We might only want to have a place on the UI for error messages. I only knew it was a 'duplicate key' by going into the browser javascript console in a debugging session.

I agree with your suggestion, and we actually have an issue filed for this already: https://github.com/multinet-app/multinet-client/issues/3. Thanks for the bug report, Curt!
