### ISSUE TITLE
Hyphens in table names cause AQL failures

### ISSUE THREAD

**Issue by JackWilb** [multinet-app/multinet-server#434]
Table names may have the following characters a-z, A-Z, 0-9, -, _ as per the arango documentation [here](https://www.arangodb.com/docs/stable/data-modeling-naming-conventions-collection-and-view-names.html). However, when the table has a "-" in the name, arango can sometimes treat it as a subtraction of 2 elements (see [here](https://www.arangodb.com/docs/stable/aql/fundamentals-syntax.html#names) for details). 

That last documentation link suggests that tables names be enclosed in backticks to prevent the AQL interpreter considering the dashes to be arithmetic operators. We'll need to go through our codebase and replace the collection names with the original enclosed in backticks.

For reference, the table sparked this investigation is `preCovid-19_flights_edges` and the error that would be thrown when trying to run `RETURN LENGTH(preCovid-19_flights_edges)` was 
```
Query: AQL: syntax error, unexpected identifier, expecting ) near '_flights_edges)' at position 1:26 (while parsing)
```

The code that generated this error is [here](https://github.com/multinet-app/multinet-server/blob/master/multinet/db.py#L324-L329) in the db.py file and is likely where we need to fix this problem.

**Comment by JackWilb** [comment]
Should we prefer using bind vars here, instead?

**Comment by waxlamp** [comment]
Yes, we probably should. I'll address this in #435.
