### ISSUE TITLE
Consider replacing existing cache system with memcached

### ISSUE THREAD

**Issue by AlmightyYakob** [multinet-app/multinet-server#453]
Our current caching system is pretty barbaric. In production we run several workers with `gunicorn`, and because our use of `lru_cache` only applies to each worker, this can lead to sporadic and undesired behavior in production. [Here's](https://krzysztofzuraw.com/blog/2017/gunicorn-lru-cache-pitfall.html) an article describing this exact situation.

I realize caching is a code smell, but I'd wager one of the biggest reasons for that is our implementation. Some of the notable issues with our current caching setup:

* No synchronization between workers
* Potential to poison the cache by directly modifying the return of a cached function, thereby updated the cache itself

Both of these can be fixed by using an actual caching system. There's well defined ways to deal with caching across multiple workers, one of which being memcached. Heroku even has a [guide](https://devcenter.heroku.com/articles/flask-memcache#add-caching-to-flask) for adding memcached to an application. Another option is Redis, but I feel like that's adding more complexity than is necessary for our needs.

Ideally we wouldn't use caching, but since our application is setup in a distributed manner, we may see too many performance hits without a caching system at all. If we use a designated caching system like memcached, then there's no longer a synchronization issue between workers, and would shift the potential for error to our implementation, which hopefully is good.

Let me know what you guys think.

**Comment by waxlamp** [comment]
This is a good idea. I don't know much about memcached personally but I know we have used it plenty across projects in D&A.

If we decided to use memcached, would it *completely* replace our ad hoc usage of `@lru_cache`? It would be something we'd use in production but not worry about locally for development, right?

If the answer to those two things is "yes", then I'd say to go ahead and write an RFC describing how we would use it in production.

Thanks for bringing this up. I agree with you (as long as the devops work is not too costly to set this up) that this is a far better solution than the "barbaric" thing we're currently doing.
