### ISSUE TITLE
Consider adding 401 as an expected response in the documentation for routes that require permissions

### ISSUE THREAD

**Issue by JackWilb** [multinet-app/multinet-server#475]
For example, running the test on the API docs for `/api/workspaces/<workspace>/permissions` gives 401 unauthorized.

Also, with the changes to the authentication 401 will likely be returned in most cases. This might be a larger problem for testing the API routes with the `/apidocs` endpoint

**Comment by waxlamp** [comment]
> Also, with the changes to the authentication 401 will likely be returned in most cases. This might be a larger problem for testing the API routes with the `/apidocs` endpoint

1. Why do you expect more 401s?
2. Why would that be a problem?

**Comment by JackWilb** [comment]
The apidocs isn't set up to use the loginToken so it will never be authenticated with the API, thus more 401s. It's a problem, because it means the apidocs page won't work for a majority of use cases

**Comment by waxlamp** [comment]
Technical debt for our switch to tokens seems to be piling up. The major problems so far are
1. We've lost the "logged in across all multinet.app apps" feature, without a good replacement
2. The Swagger docs no longer work properly

I am starting to be inclined to go back to cookies (despite the potential for CSRF attacks) while we fully research the "right" way to go about this.

@AlmightyYakob, what are your thoughts?

**Comment by AlmightyYakob** [comment]
> Technical debt for our switch to tokens seems to be piling up. The major problems so far are
> 
> 1. We've lost the "logged in across all multinet.app apps" feature, without a good replacement
> 2. The Swagger docs no longer work properly
> 
> I am starting to be inclined to go back to cookies (despite the potential for CSRF attacks) while we fully research the "right" way to go about this.
> 
> @AlmightyYakob, what are your thoughts?

I'm okay with going back to using cookies, CSRF attacks are a very specific and unlikely scenario for us. #472 is the PR that switched from cookies to headers, and most of that is actually independent of if  we use cookies vs headers (mostly focused on JWTs and test fixtures, but still improvements to the code base IMO). The switch to using headers was probably impulsive anyway. If we'd like I can make an issue for this and address it soon, with corresponding PRs in the client as well.

**Comment by waxlamp** [comment]
> > Technical debt for our switch to tokens seems to be piling up. The major problems so far are
> > 
> > 1. We've lost the "logged in across all multinet.app apps" feature, without a good replacement
> > 2. The Swagger docs no longer work properly
> > 
> > I am starting to be inclined to go back to cookies (despite the potential for CSRF attacks) while we fully research the "right" way to go about this.
> > @AlmightyYakob, what are your thoughts?
> 
> I'm okay with going back to using cookies, CSRF attacks are a very specific and unlikely scenario for us. #472 is the PR that switched from cookies to headers, and most of that is actually independent of if we use cookies vs headers (mostly focused on JWTs and test fixtures, but still improvements to the code base IMO). The switch to using headers was probably impulsive anyway. If we'd like I can make an issue for this and address it soon, with corresponding PRs in the client as well.

That would be great. I'm getting the sense that you believe that switch back to cookies would be not a lot of work--is that right?

**Comment by AlmightyYakob** [comment]
> That would be great. I'm getting the sense that you believe that switch back to cookies would be not a lot of work--is that right?

Yes, it's mainly a matter of switching where we grab the token from - the request headers or the passed along cookies. I actually think most of the work will be in the client, even though it still shouldn't be too much work.
