### ISSUE TITLE
Remove "entity metadata" concept

### ISSUE THREAD

**Issue by waxlamp** [multinet-app/multinet-server#491]
In a discussion with @AlmightyYakob, we decided that we don't have a compelling need to combine table and network metadata types together in one "entity type" model, because it will likely complicate the logic for teasing apart the metadata types in later processing.

The plan for now is to remove the `EntityMetadata` and `GraphMetadata` models, and reconstitute the network metadata concept if and when it is needed.

Relevant code: https://github.com/multinet-app/multinet-server/blob/2cf8989b61bf3d9cf152e7df8cb462e41351f1d9/multinet/types.py#L12-L34

**Comment by AlmightyYakob** [comment]
O

**Comment by AlmightyYakob** [comment]
Once integration with `multinetjs` is added, this change will have to be applied there as well.
