### ISSUE TITLE
Limit Runtime and Memory of AQL Queries

### ISSUE THREAD

**Issue by AlmightyYakob** [multinet-app/multinet-server#500]
Currently, there's no runtime or memory limit on AQL queries, which is dangerous, especially if the project will gain publicity in the future. [Here](https://www.arangodb.com/docs/stable/programs-arangod-query.html#limiting-query-runtime) the ArangoDB docs mention limits that can be specified both at app start time (with env vars), or per query with query arguments. Regardless of which approach we choose, I think it should be done, so that the AQL endpoint isn't a vector to halt our app entirely (intentionally or otherwise).

My preference would be to go with the latter approach, since it would require less configuration on our part, and imposing system-wide limits on queries could impede system operations like backups, etc.

Our ArangoDB Python API (python-arango) has an option for specifying both limits per query ([AQL execute function](https://python-driver-for-arangodb.readthedocs.io/en/master/specs.html?highlight=execute#arango.aql.AQL.execute)), which seems like a good place to start if nothing else.

**Comment by waxlamp** [comment]
Good thinking. Can you set those per-query limits as you envision, and perhaps see about returning a special timeout error if those limits are exceeded?

**Comment by AlmightyYakob** [comment]
> Good thinking. Can you set those per-query limits as you envision, and perhaps see about returning a special timeout error if those limits are exceeded?

I'm not sure what kind of error is returned on timeout, I can see about that. But it should just be a matter of passing arguments to our existing queries run from the AQL endpoint.
