### ISSUE TITLE
Issue converting some values to boolean

### ISSUE THREAD

**Issue by JackWilb** [multinet-app/multinet-server#502]
I'm trying to upload a csv with the following data:

```
_key,followers_count,query_tweet_count,friends_count,statuses_count,listed_count,favourites_count,count_followers_in_query,screen_name,profile_image_url,influential,original
27546319,4094,0,5000,17876,208,47742,9,roboticwrestler,http://pbs.twimg.com/profile_images/1047978249446469640/0s5SdWHj_normal.jpg,True,False
765548,115984,0,1619,18015,5385,13298,9,hmason,http://pbs.twimg.com/profile_images/948689418709323777/sTBM3vG0_normal.jpg,True,False
```

Note the last 2 columns are boolean. The client parser for these seems to be working okay (it thought influential was category and original was boolean), but when I go to upload I get errors parsing and converting the values for influential and original. Are "True", "False" not acceptable values for it? Did we document what the allowed pairs are?

**Comment by JackWilb** [comment]
Worked with a conversion to "true", "false"

**Comment by waxlamp** [comment]
The allowed values for boolean columns are the ones allowed by the [YAML spec](https://yaml.org/type/bool.html); notice that `True` and `False` are both allowed. We must have a missing case in our converter. Thanks for the issue report.
