### ISSUE TITLE
Add CloudWatch Events to schedule a nightly backup of the database 

### ISSUE THREAD

**Issue by JackWilb** [multinet-app/multinet-server#504]
[Relevant docs](https://docs.aws.amazon.com/AmazonCloudWatch/latest/events/TakeScheduledSnapshot.html)

We need to set up a nightly backup of the data so we can restore in case of emergency. This is especially important as we're planning to merge #492

**Comment by JackWilb** [comment]
I set this up with @AlmightyYakob to back up the db.multinet.app instance everyday. Backups are incremental (but deleting one backup shouldn't lose us any data, other than the unique data in that snapshot) so shouldn't cost too much.

We'll monitor for cost ,and if it's really high for some reason we'll revisit this to see if there's a better way to do the back ups. 

I'm going to leave this issue open for a little while to test if the schedule works as intended.

**Comment by JackWilb** [comment]
I set this up with @AlmightyYakob to back up the db.multinet.app instance everyday. Backups are incremental (but deleting one backup shouldn't lose us any data, other than the unique data in that snapshot) so shouldn't cost too much.

We'll monitor for cost ,and if it's really high for some reason we'll revisit this to see if there's a better way to do the back ups. 

I'm going to leave this issue open for a little while to test if the schedule works as intended.

**Comment by waxlamp** [comment]
Thank you both (@JackWilb and @AlmightyYakob) for setting this up. Don't forget to claim your joint credit at this week's group meeting!

What's the order of magnitude of cost we're expecting?

**Comment by JackWilb** [comment]
It's using S3 and the backup size is 50GB (+/- a little for the blocks that change). That should mean, at $0.023 per GB, $1.15 per month

**Comment by waxlamp** [comment]
"For less than the price of a cup of coffee..."

**Comment by JackWilb** [comment]
I've verified that it's working with the automated backup taking place at 1:19:29 PM UTC-7 each of the past 3 days. I'll monitor cost, but I don't think we need an issue for that.
